[build-system]
requires = [
    "typing-extensions>=4",
    "setuptools>=42",
    "scikit-build>=0.15.0",
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.cibuildwheel]
test-command = "pytest {project}/tests"
test-extras = ["test"]
test-skip = ["*universal2:arm64"]
